POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "Victor",
    "email": "victor@victor.com",
    "password": "123456",
    "cellphone": "1234567890",
    "role": "ADMIN"
}
###
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "victor@victor.com",
    "password": "123456"
}